### ISSUE TITLE
Extend `Resource` prototype

### ISSUE THREAD

**Issue by joshuajabbour** [basti1302/halfred#1]
I'd really love to be able to extend `Resource` by adding my own methods to the prototype.

(Related request, though not one I need: Might be nice to be able to provide your own `Resource` class to the parser.)

**Comment by joshuajabbour** [comment]
Couple of options to make this possible. In `halfred.js`, either exporting `Resource` or something like this would do the trick: 

```js
extend: function(callback) {
  callback({
    Resource: Resource,
    Parser: Parser
  });
}
```

Any thoughts?

**Comment by basti1302** [comment]
Would be okay for me. Both options seem okay, I have a slight preference for simply exporting it like this: https://github.com/basti1302/traverson/blob/2.0.1/traverson.js#L13

Is there any use case for exporting the Parser?

**Comment by basti1302** [comment]
Btw, you're welcome to go forward with a PR on this :-)

**Comment by joshuajabbour** [comment]
Exporting would be much simpler, so if you're fine with that, I am as well. The alternative was just in case you didn't want it that visible. Done: https://github.com/basti1302/halfred/pull/2

As for the Parser, I have no use for it being exported, but I can easily imagine someone else. Though since all of the logic is hidden away in private functions, it would be difficult to extend.
